[package]
name = "bevis-derive"
version = "0.1.0"
edition = "2021"
authors = ["Mathias Hall-Andersen"]
repository = "https://github.com/rot256/bevis"
license = "MIT"

[lib]
bevis = "0.1"
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1"
proc-macro2 = "1.0"
